Fix issue 1354 (always using same product_mini path_format)
thirtybees/thirtybees pull request #1415
Opened 2022-04-06 12:50 UTC by eschiendorfer

I am experiencing this issue https://github.com/thirtybees/thirtybees/issues/1354 since years as well. That's why I tried to fix it.

As you can read in the issue notes: the BO uses different paths. I tried to find all product_mini usages and changed the code to the following format: **product_mini_{$id_product}_{$id_shop}.jpg**.

Why not using id_product_attribute (as some parts of the code did)? Either I am getting it wrong or this makes no sense at all. product_mini is the cover image in a small cached format. There is no way, you could save the cover image related to a product_attribute. You can only save different covers for different shops. Of course one could discuss, if this option should be added, but for now it's simpler to just us the path_format with $id_shop.

Note: This PR should be tested by at least another person. Neither did I test this a lot, nor do I use a lot of product_attributes.

2022-05-27 11:46 UTC, getdatakick commented
I believe it is wrong to drop attribute id from `product_mini_*` images. For example, in order detail list or in cart products list we want to display correct image for combination in cart, not product cover image.

2022-05-27 11:49 UTC, getdatakick requested changes
product mini should contain `id_product`, `id_attribute`, and `id_shop` identifiers

2022-05-29 00:54 UTC, eschiendorfer commented
I understand. But, what would the correct image be for a combination? Just the first one that exists? I can just tell for my shop: that would always be the same. Not a problem for me, but I believe the only clean solution would be the introduction of cover image per attribute. But that would be a huge rewrite...

2022-05-29 06:55 UTC, getdatakick commented
Let's then remove product and combination from the question. How about we replaced all occurrences of `product_mini_{product_id}*` with `image_mini_{id_image}`. After all, that's what we are trying to do here -- retrieve the miniature of specific image, and it shouldn't really matter to which product or combination this image is associated with.

While we are at that, we could also replace `product_{product_id}` with `image_{image_id}`

2022-06-22 09:24 UTC, getdatakick commented
Instead of product_mini, we now use image_mini in the core. See commit. 
Thanks for the PR.

2022-06-22 09:24 UTC, closed without merging